version: '3'

services:
  aquinas-bot:
    image: aquinas-bot
    container_name: aquinas-bot
    hostname: aquinas-bot
    build:
      dockerfile: ./apps/aquinas-bot/Dockerfile
      tags:
        - 'aquinas-bot:latest'
    env_file:
      - ./apps/aquinas-bot/.env.production
    ports:
      - 4201:4200

networks:
  default:
    name: prod_network
    driver: bridge
